from typing import Optional, Tuple, Union, overload
from .__base import (Number, Shape, DataType, ArrayLike)

class Backend:
    def __eq__(self, arg0: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __init__(self, arg0: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, arg0: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, arg0: int) -> None: ...
    @property
    def name(self) -> str:...
    CPU: shapelets.compute._pygauss.Backend # value = <Backend.CPU: 1>
    CUDA: shapelets.compute._pygauss.Backend # value = <Backend.CUDA: 2>
    Default: shapelets.compute._pygauss.Backend # value = <Backend.Default: 0>
    OpenCL: shapelets.compute._pygauss.Backend # value = <Backend.OpenCL: 4>
    __members__: dict # value = {'Default': <Backend.Default: 0>, 'CPU': <Backend.CPU: 1>, 'CUDA': <Backend.CUDA: 2>, 'OpenCL': <Backend.OpenCL: 4>}

class BorderType:
    def __eq__(self, arg0: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __init__(self, arg0: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, arg0: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, arg0: int) -> None: ...
    @property
    def name(self) -> str:...
    ClampEdge: shapelets.compute._pygauss.BorderType # value = <BorderType.ClampEdge: 2>
    Periodic: shapelets.compute._pygauss.BorderType # value = <BorderType.Periodic: 3>
    Symmetric: shapelets.compute._pygauss.BorderType # value = <BorderType.Symmetric: 1>
    Zero: shapelets.compute._pygauss.BorderType # value = <BorderType.Zero: 0>
    __members__: dict # value = {'Zero': <BorderType.Zero: 0>, 'Symmetric': <BorderType.Symmetric: 1>, 'ClampEdge': <BorderType.ClampEdge: 2>, 'Periodic': <BorderType.Periodic: 3>}

class ConvDomain:
    def __eq__(self, arg0: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __init__(self, arg0: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, arg0: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, arg0: int) -> None: ...
    @property
    def name(self) -> str:...
    Auto: shapelets.compute._pygauss.ConvDomain # value = <ConvDomain.Auto: 0>
    Frequency: shapelets.compute._pygauss.ConvDomain # value = <ConvDomain.Frequency: 2>
    Spatial: shapelets.compute._pygauss.ConvDomain # value = <ConvDomain.Spatial: 1>
    __members__: dict # value = {'Auto': <ConvDomain.Auto: 0>, 'Frequency': <ConvDomain.Frequency: 2>, 'Spatial': <ConvDomain.Spatial: 1>}

class ConvMode:
    def __eq__(self, arg0: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __init__(self, arg0: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, arg0: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, arg0: int) -> None: ...
    @property
    def name(self) -> str:...
    Default: shapelets.compute._pygauss.ConvMode # value = <ConvMode.Default: 0>
    Expand: shapelets.compute._pygauss.ConvMode # value = <ConvMode.Expand: 1>
    __members__: dict # value = {'Default': <ConvMode.Default: 0>, 'Expand': <ConvMode.Expand: 1>}

class DeviceInfo:
    def __repr__(self) -> str: ...
    @property
    def compute(self) -> str: ...
    @property
    def id(self) -> int: ...
    @property
    def isDoubleAvailable(self) -> bool: ...
    @property
    def isHalfAvailable(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def platform(self) -> str: ...

class DeviceMemory:
    def __repr__(self) -> str: ...
    @property
    def buffers(self) -> int: ...
    @property
    def bytes(self) -> int: ...
    @property
    def locked_buffers(self) -> int: ...
    @property
    def locked_bytes(self) -> int: ...

class MatrixProfile:
    def __init__(self, arg0: ShapeletsArray, arg1: ShapeletsArray) -> None: ...
    @property
    def index(self) -> ShapeletsArray: ...
    @index.setter
    def index(self, arg0: ShapeletsArray) -> None: ...
    @property
    def profile(self) -> ShapeletsArray: ...
    @profile.setter
    def profile(self, arg0: ShapeletsArray) -> None: ...

class MatrixProperties:
    def __eq__(self, arg0: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __init__(self, arg0: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, arg0: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, arg0: int) -> None: ...
    @property
    def name(self) -> str:...
    BlockDiagonal: shapelets.compute._pygauss.MatrixProperties # value = <MatrixProperties.Symmetric: 512>
    Conjugated: shapelets.compute._pygauss.MatrixProperties # value = <MatrixProperties.Conjugated: 4>
    ConjugatedTransposed: shapelets.compute._pygauss.MatrixProperties # value = <MatrixProperties.ConjugatedTransposed: 2>
    Default: shapelets.compute._pygauss.MatrixProperties # value = <MatrixProperties.Default: 0>
    Lower: shapelets.compute._pygauss.MatrixProperties # value = <MatrixProperties.Lower: 64>
    Orthogonal: shapelets.compute._pygauss.MatrixProperties # value = <MatrixProperties.Orthogonal: 2048>
    PositiveDefinite: shapelets.compute._pygauss.MatrixProperties # value = <MatrixProperties.PositiveDefinite: 1024>
    Symmetric: shapelets.compute._pygauss.MatrixProperties # value = <MatrixProperties.Symmetric: 512>
    Transposed: shapelets.compute._pygauss.MatrixProperties # value = <MatrixProperties.Transposed: 1>
    TriDiagonal: shapelets.compute._pygauss.MatrixProperties # value = <MatrixProperties.TriDiagonal: 4096>
    UnitDiagonal: shapelets.compute._pygauss.MatrixProperties # value = <MatrixProperties.UnitDiagonal: 128>
    Upper: shapelets.compute._pygauss.MatrixProperties # value = <MatrixProperties.Upper: 32>
    __members__: dict # value = {'Default': <MatrixProperties.Default: 0>, 'Transposed': <MatrixProperties.Transposed: 1>, 'ConjugatedTransposed': <MatrixProperties.ConjugatedTransposed: 2>, 'Conjugated': <MatrixProperties.Conjugated: 4>, 'Upper': <MatrixProperties.Upper: 32>, 'Lower': <MatrixProperties.Lower: 64>, 'UnitDiagonal': <MatrixProperties.UnitDiagonal: 128>, 'Symmetric': <MatrixProperties.Symmetric: 512>, 'PositiveDefinite': <MatrixProperties.PositiveDefinite: 1024>, 'Orthogonal': <MatrixProperties.Orthogonal: 2048>, 'TriDiagonal': <MatrixProperties.TriDiagonal: 4096>, 'BlockDiagonal': <MatrixProperties.Symmetric: 512>}

class NormType:
    def __eq__(self, arg0: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __init__(self, arg0: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, arg0: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, arg0: int) -> None: ...
    @property
    def name(self) -> str: ...
    Euclid: shapelets.compute._pygauss.NormType # value = <NormType.Vector2: 2>
    LPQ: shapelets.compute._pygauss.NormType # value = <NormType.LPQ: 7>
    Matrix: shapelets.compute._pygauss.NormType # value = <NormType.Matrix: 4>
    MatrixInf: shapelets.compute._pygauss.NormType # value = <NormType.MatrixInf: 5>
    Singular: shapelets.compute._pygauss.NormType # value = <NormType.Singular: 6>
    Vector1: shapelets.compute._pygauss.NormType # value = <NormType.Vector1: 0>
    Vector2: shapelets.compute._pygauss.NormType # value = <NormType.Vector2: 2>
    VectorInf: shapelets.compute._pygauss.NormType # value = <NormType.VectorInf: 1>
    VectorP: shapelets.compute._pygauss.NormType # value = <NormType.VectorP: 3>
    __members__: dict # value = {'Vector1': <NormType.Vector1: 0>, 'VectorInf': <NormType.VectorInf: 1>, 'Vector2': <NormType.Vector2: 2>, 'VectorP': <NormType.VectorP: 3>, 'Matrix': <NormType.Matrix: 4>, 'MatrixInf': <NormType.MatrixInf: 5>, 'Singular': <NormType.Singular: 6>, 'LPQ': <NormType.LPQ: 7>, 'Euclid': <NormType.Vector2: 2>}

class ParallelFor:
    def __iter__(self) -> ParallelFor: ...
    def __next__(self) -> ParallelFor: ...

class ScanOp:
    def __eq__(self, arg0: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __init__(self, arg0: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, arg0: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, arg0: int) -> None: ...
    @property
    def name(self) -> str: ...
    Add: shapelets.compute._pygauss.ScanOp # value = <ScanOp.Add: 0>
    Max: shapelets.compute._pygauss.ScanOp # value = <ScanOp.Max: 3>
    Min: shapelets.compute._pygauss.ScanOp # value = <ScanOp.Min: 2>
    Mul: shapelets.compute._pygauss.ScanOp # value = <ScanOp.Mul: 1>
    __members__: dict # value = {'Add': <ScanOp.Add: 0>, 'Mul': <ScanOp.Mul: 1>, 'Min': <ScanOp.Min: 2>, 'Max': <ScanOp.Max: 3>}

class ScopedBatch:
    def __enter__(self) -> None: ...
    def __exit__(self, *args) -> None: ...

class ShapeletsArray:
    def __add__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __and__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __copy__(self) -> ShapeletsArray: ...
    def __deepcopy__(self, memo: object) -> ShapeletsArray: ...
    def __eq__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __ge__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __getitem__(self, selector: object) -> ShapeletsArray: ...
    def __gt__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __iadd__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __iand__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __ilshift__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __imod__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __imul__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __ior__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __ipow__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __irshift__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __isub__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __itruediv__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __ixor__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __le__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __lshift__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __lt__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __matmul__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __mod__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __mul__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __ne__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __neg__(self) -> ShapeletsArray: ...
    def __or__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __pow__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __radd__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __rand__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __repr__(self) -> str: ...
    def __rlshift__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __rmatmul__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __rmod__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __rmul__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __ror__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __rpow__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __rrshift__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __rshift__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __rsub__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __rtruediv__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __rxor__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __setitem__(self, selector: object, value: ArrayLike) -> ShapeletsArray: ...
    def __sub__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __truediv__(self, other: ArrayLike) -> ShapeletsArray: ...
    def __xor__(self, other: ArrayLike) -> ShapeletsArray: ...
    def astype(self, type: DataType) -> ShapeletsArray: ...
    def display(self, precision: int = 4, transpose: bool = True) -> None: ...
    def same_as(self, arr_like: ArrayLike, eps: float_ = 0.0001) -> bool: ...
    @property
    def H(self) -> ShapeletsArray:...
    @property
    def T(self) -> ShapeletsArray:...
    @property
    def backend(self) -> Backend: ...
    @property
    def dtype(self) -> DataType: ...
    @property
    def is_column(self) -> bool: ...
    @property
    def is_row(self) -> bool: ...
    @property
    def is_single(self) -> bool: ...
    @property
    def is_vector(self) -> bool: ...
    @property
    def itemsize(self) -> int: ...
    @property
    def ndim(self) -> int: ...
    @property
    def shape(self) -> Shape: ...
    @property
    def size(self) -> int: ...
    __array_priority__ = 30
    __hash__ = None

