from .__basic_typing import ArrayLike
from ._array_obj import ShapeletsArray

def iscomplex(array_like: ArrayLike) -> ShapeletsArray: ...

def isfinite(array_like: ArrayLike) -> ShapeletsArray: ...

def isinf(array_like: ArrayLike) -> ShapeletsArray: ...

def isnan(array_like: ArrayLike) -> ShapeletsArray: ...

def isreal(array_like: ArrayLike) -> ShapeletsArray: ...

def logical_and(left: ArrayLike, right: ArrayLike) -> ShapeletsArray: ...

def logical_not(array_like: ArrayLike) -> ShapeletsArray: ...

def logical_or(left: ArrayLike, right: ArrayLike) -> ShapeletsArray: ...

def not_equal(left: ArrayLike, right: ArrayLike) -> ShapeletsArray: ...

def equal(left: ArrayLike, right: ArrayLike) -> ShapeletsArray: ...

def greater(left: ArrayLike, right: ArrayLike) -> ShapeletsArray: ...

def greater_equal(left: ArrayLike, right: ArrayLike) -> ShapeletsArray: ...

def less(left: ArrayLike, right: ArrayLike) -> ShapeletsArray: ...

def less_equal(left: ArrayLike, right: ArrayLike) -> ShapeletsArray: ...
