from . import _pygauss
from .__basic_typing import ArrayLike
from ._array_obj import ShapeletsArray

class DistanceType:
    def __eq__(self, arg0: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __init__(self, arg0: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, arg0: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, arg0: int) -> None: ...
    @property
    def name(self) -> str: ...
    Abs_Euclidean: _pygauss.DistanceType 
    Additive_Symm_Chi: _pygauss.DistanceType 
    Avg_L1_Linf: _pygauss.DistanceType 
    Bhattacharyya: _pygauss.DistanceType 
    Canberra: _pygauss.DistanceType 
    Chebyshev: _pygauss.DistanceType 
    Clark: _pygauss.DistanceType 
    Cosine: _pygauss.DistanceType 
    Czekanowski: _pygauss.DistanceType 
    Dice: _pygauss.DistanceType 
    Divergence: _pygauss.DistanceType 
    DTW: _pygauss.DistanceType 
    Euclidean: _pygauss.DistanceType 
    Fidelity: _pygauss.DistanceType 
    Gower: _pygauss.DistanceType 
    Hamming: _pygauss.DistanceType 
    Harmonic_mean: _pygauss.DistanceType 
    Hellinger: _pygauss.DistanceType 
    Innerproduct: _pygauss.DistanceType 
    Intersection: _pygauss.DistanceType 
    Jaccard: _pygauss.DistanceType 
    Jeffrey: _pygauss.DistanceType 
    Jensen_Difference: _pygauss.DistanceType 
    Jensen_Shannon: _pygauss.DistanceType 
    K_Divergence: _pygauss.DistanceType 
    Kulczynski: _pygauss.DistanceType 
    Kullback: _pygauss.DistanceType 
    Kumar_Johnson: _pygauss.DistanceType 
    Kumar_Hassebrook: _pygauss.DistanceType 
    Lorentzian: _pygauss.DistanceType 
    Manhattan: _pygauss.DistanceType 
    Matusita: _pygauss.DistanceType 
    Max_Symmetric_Chi: _pygauss.DistanceType 
    Min_Symmetric_Chi: _pygauss.DistanceType 
    Minkowshi: _pygauss.DistanceType 
    MPDist: _pygauss.DistanceType 
    Neyman: _pygauss.DistanceType 
    Pearson: _pygauss.DistanceType 
    Prob_Symmetric_Chi: _pygauss.DistanceType 
    SBD: _pygauss.DistanceType 
    Soergel: _pygauss.DistanceType 
    Sorensen: _pygauss.DistanceType 
    Square_Chord: _pygauss.DistanceType 
    Squared_Chi: _pygauss.DistanceType 
    Squared_Euclidean: _pygauss.DistanceType 
    Taneja: _pygauss.DistanceType 
    Topsoe: _pygauss.DistanceType 
    Vicis_Wave_Hedges: _pygauss.DistanceType 
    Wave_Hedges: _pygauss.DistanceType 
    __members__: dict

def pdist(tss: ArrayLike, metric: DistanceType, **kwargs) -> ShapeletsArray: ...
def cdist(xa: ArrayLike, xb: ArrayLike, metric: DistanceType, **kwargs) -> ShapeletsArray:  ...

def abs_euclidean(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def additive_symm_chi(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def avg_l1_linf(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def bhattacharyya(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def canberra(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def chebyshev(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def clark(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def cosine(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def czekanowski(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def dice(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def divergence(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def dtw(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def euclidean(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def fidelity(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def gower(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def hamming(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def harmonic_mean(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def hellinger(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def innerproduct(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def intersection(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def jaccard(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def jeffrey(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def jensen_difference(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def jensen_shannon(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def k_divergence(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def kulczynski(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def kullback(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def kumar_johnson(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def kumarhassebrook(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def lorentzian(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def manhattan(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def matusita(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def max_symmetric_chi(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def min_symmetric_chi(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...

def minkowshi(a: ArrayLike, b: ArrayLike, p: float) -> ShapeletsArray: ...
def mpdist(a: ArrayLike, b: ArrayLike, w: int, threshold: float = 0.05) -> ShapeletsArray: ...

def neyman(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def pearson(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def prob_symmetric_chi(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def sbd(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def soergel(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def sorensen(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def square_chord(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def squared_chi(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def squared_euclidean(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def taneja(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def topsoe(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def vicis_wave_hedges(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...
def wavehedges(a: ArrayLike, b: ArrayLike) -> ShapeletsArray: ...



# Abs_Euclidean
# Additive_Symm_Chi
# Avg_L1_Linf
# Bhattacharyya
# Canberra
# Chebyshe
# Chebyshev
# Clark
# Cosine
# Czekanowski
# Cice
# Civergence
# DTW
# Euclidean
# Fidelity
# Gower
# Hamming
# Harmonic_mean
# Hellinger
# Innerproduct
# Intersection
# Jaccard
# Jeffrey
# Jensen_Difference
# Jensen_Shannon
# K_Divergence
# Kulczynski
# Kullback
# Kumar_Johnson
# Kumar_Hassebrook
# Lorentzian
# Manhattan
# Matusita
# Max_Symmetric_Chi
# Min_Symmetric_Chi
# Minkowshi
# MPDist
# Neyman
# Pearson
# Prob_Symmetric_Chi
# SBD
# Soergel
# Sorensen
# Square_Chord
# Squared_Chi
# Squared_Euclidean
# Taneja
# Topsoe
# Vicis_Wave_Hedges
# Wave_Hedges