from .__basic_typing import ArrayLike
from ._array_obj import ShapeletsArray

def decimal_scaling(array_like: ArrayLike) -> ShapeletsArray: ...
def minmax_norm(array_like: ArrayLike, high: float = 1.0, low: float = 0.0) -> ShapeletsArray: ...
def mean_norm(array_like: ArrayLike) -> ShapeletsArray: ...
def zscore(array_like: ArrayLike) -> ShapeletsArray: ...
def unit_length_norm(array_like: ArrayLike) -> ShapeletsArray: ...
def median_norm(array_like: ArrayLike) -> ShapeletsArray: ...
def logistic_norm(array_like: ArrayLike) -> ShapeletsArray: ...
def tanh_norm(array_like: ArrayLike) -> ShapeletsArray: ...
